config/routes.rb
Rails.application.routes.draw do



  scope "(:locale)", locale: /id|en/ do
    resources :ecommerce_products
    resources :ecommerces
    resources :discoverproducts
    resources :request_samples
    root 'pages#home'
    get 'app' => "app#index"
    get 'dashboard' => "app#index"

    get 'contact-us', to: 'pages#contact', as: :contact_us
    get 'home/discoverourproduct', to: 'pages#discoverourproduct', as: :discoverourproduct
    get 'discoverourproduct', to: 'pages#discoverourproduct'
    resources :users
    resources :setups
    resources :stores do
      collection { post :import }
    end
    resources :beasellers do
      collection { post :import }
    end
    resources :image_events
    resources :events
    resources :articles
    resources :image_products
    resources :product_categories
    resources :products
    devise_for :users,
    path:'user',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }
     get 'simulasi-keuntungan', to: 'pages#simulasikeuntungan', as: :simulasikeuntungan
     get 'beaseller', to: 'pages#beaseller', as: :crt_beaseller
     get 'requestsample', to: 'pages#requestsample', as: :crt_requestsample
     get 'list-page', to: 'pages#index', as: :list_pages
     get 'store-location', to: 'pages#storelocation', as: :storelocation

     get '/product', to: 'pages#list_product', as: :list_product
     get 'product/:id', to: 'product_categories#show', as: :dtl_product_category
     get 'product/:category_name/:id/', to: 'products#show', as: :dtl_product

     get '/thankspage', to: 'pages#thankspage', as: :thankspage
     get '/news-and-event', to: 'pages#list_blog', as: :gallery
     get '/blog', to: 'pages#list_blog', as: :list_blog
     get 'blog/:id', to: 'articles#show', as: :dtl_blog
     get '/event', to: 'pages#list_event', as: :list_event
     get '/event/:id', to: 'events#show', as: :dtl_event

     resources :pages, path: ''
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/setup.rb
class Setup < ApplicationRecord
  mount_uploader :site_image, LogoUploader
  mount_uploader :site_favicon, IconUploader
  mount_uploader :image_share, ImageUploader
  mount_uploader :hero_image, ImageUploader
  mount_uploader :main_image, ImageUploader
  mount_uploader :background, ImageUploader
  mount_uploader :effek_1, ImageUploader
  mount_uploader :effek_2, ImageUploader
  mount_uploader :effek_3, ImageUploader
  mount_uploader :effek_4, ImageUploader
  validates :site_name, presence: true
  validates :site_title, presence: true
  validates :site_url, presence: true

  def remove_image=(val)
    image_will_change! if val
    super
  end
end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController
  before_action :set_setup, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'admin'
  # GET /setups
  # GET /setups.json
  # def index
  #   @setups = Setup.all
  # end

  # GET /setups/1
  # GET /setups/1.json
  def show
    redirect_to edit_setup_path(1)
  end

  # GET /setups/new
  def new
    # @setup = Setup.new
    redirect_to edit_setup_path(1)
  end

  # GET /setups/1/edit
  def edit
  end

  # POST /setups
  # POST /setups.json
  def create
    redirect_to edit_setup_path(1)
    # @setup = Setup.new(setup_params)
    #
    # respond_to do |format|
    #   if @setup.save
    #     format.html { redirect_to @setup, notice: 'Setup was successfully created.' }
    #     format.json { render :show, status: :created, location: @setup }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @setup.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /setups/1
  # PATCH/PUT /setups/1.json
  def update
    respond_to do |format|
      if @setup.update(setup_params)
        format.html { redirect_to @setup, notice: 'Setup was successfully updated.' }
        format.json { render :show, status: :ok, location: @setup }
      else
        format.html { render :edit }
        format.json { render json: @setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setups/1
  # DELETE /setups/1.json
  # def destroy
  #   @setup.destroy
  #   respond_to do |format|
  #     format.html { redirect_to setups_url, notice: 'Setup was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setup
      @setup = Setup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setup_params
      params.require(:setup).permit(:site_name, :site_title, :site_description, :site_keywords, :site_url, :site_image, :site_favicon, :facebook, :twitter, :instagram, :phone, :contact, :google_map, :image_share, :custom_code, :hero_status, :hero_image, :background, :main_image, :effek_1, :effek_2, :effek_3, :effek_4, :remove_main, :remove_effek_1, :remove_effek_2, :remove_effek_3, :remove_effek_4)
    end
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/views/setups/_form.html.erb
<% if @setup.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@setup.errors.count, "error") %> prohibited this setup from being saved:</h3>
    </div>
    <div class="panel-body">
      <ul>
        <% @setup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>
<%= form_for @setup, :html => { :class => "form-horizontal setup" } do |f| %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-12">
            <%= f.label :image_share, :class => 'control-label' %> <small><i>Logo Website</i></small>
            <p>Max File Size 500KB</p>
            <% if @setup.image_share.nil? || @setup.image_share.blank? %>
              <%= f.file_field :image_share, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K', 'data-allowed-file-extensions'=>'jpg jpeg png' %>
            <% else %>
              <%= f.file_field :image_share, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K', 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-default-file' => @setup.image_share.url %>
            <% end %>
            <%=f.error_span(:image_share) %>
          </div>
          <div class="col-md-6">
            <%= f.label :site_image, :class => 'control-label' %> <small><i>Logo Website</i></small>
            <p>Max File Size 500KB</p>
            <% if @setup.site_image.nil? || @setup.site_image.blank? %>
              <%= f.file_field :site_image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K', 'data-allowed-file-extensions'=>'jpg jpeg png' %>
            <% else %>
              <%= f.file_field :site_image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K', 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-default-file' => @setup.site_image.url %>
            <% end %>
            <%=f.error_span(:site_image) %>
          </div>
          <div class="col-md-6">
            <%= f.label :site_favicon, :class => 'control-label' %> <small><i>Favicon Website</i></small>
            <p>Max File Size 100KB | Max Width and Height 64px</p>
            <% if @setup.site_favicon.nil? || @setup.site_favicon.blank? %>
              <%= f.file_field :site_favicon, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'100K', 'data-max-width'=>'65', 'data-max-height'=>'65', 'data-allowed-file-extensions'=>'jpg jpeg png svg', 'data-allowed-formats'=>'square' %>
            <% else %>
              <%= f.file_field :site_favicon, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'100K', 'data-max-width'=>'65', 'data-max-height'=>'65', 'data-allowed-file-extensions'=>'jpg jpeg png svg', 'data-allowed-formats'=>'square', 'data-default-file' => @setup.site_favicon.url %>
            <% end %>
            <%=f.error_span(:site_favicon) %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-12">
            <h4>Website Identity and SEO</h4>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :site_name, :class => 'control-label' %> <small><i>required</i></small>
              <%= f.text_field :site_name, :class => 'form-control', required: true %>
              <%=f.error_span(:site_name) %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :site_title, :class => 'control-label' %> <small><i>required</i></small>
              <%= f.text_field :site_title, :class => 'form-control', required: true %>
              <%=f.error_span(:site_title) %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :site_description, :class => 'control-label' %>
              <%= f.text_area :site_description, :class => 'form-control' %>
              <%=f.error_span(:site_description) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-12">
            <%= f.hidden_field :hero_status, id:"hr-status" %>
            <h4>Custom Code</h4>
            <div id="cst-code">
              <div id="editor">
              </div>
              <%=  f.text_area :custom_code, id:'get-editor' %>
              <div class="text-center mt-3">
                <button type="button" name="button" class="btn btn-info" id="btn-fl-image">Change to full image</button>
              </div>
            </div>
            <div id="fll-image">
              <%= f.label :hero_image, :class => 'control-label' %>
              <p>Max File Size 500KB</p>
              <% if @setup.hero_image.nil? || @setup.hero_image.blank? %>
                <%= f.file_field :hero_image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K', 'data-allowed-file-extensions'=>'jpg jpeg png' %>
              <% else %>
                <%= f.file_field :hero_image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K', 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-default-file' => @setup.hero_image.url %>
              <% end %>
              <%=f.error_span(:hero_image) %>
              <div class="text-center mt-3">

              </div>
            </div>
            <div class="mt-3 text-center">
                <button type="button" name="button" class="btn btn-info" id="btn-cst-code">Change to custom code</button>
                <button type="button" name="button" class="btn btn-info" id="btn-fl-image">Change to full image</button>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-12">
            <h4>Social Media</h4>
          </div>
          <div class="col-md-3">
            <div class="form-group">
              <%= f.label :facebook, :class => 'control-label' %> <small><i>required</i></small>
              <%= f.text_field :facebook, :class => 'form-control', required: true %>
              <%=f.error_span(:facebook) %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group">
              <%= f.label :instagram, :class => 'control-label' %> <small><i>required</i></small>
              <%= f.text_field :instagram, :class => 'form-control', required: true %>
              <%=f.error_span(:instagram) %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group">
              <%= f.label :twitter, :class => 'control-label' %> <small><i>required</i></small>
              <%= f.text_field :twitter, :class => 'form-control', required: true %>
              <%=f.error_span(:twitter) %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group">
              <%= f.label :phone, :class => 'control-label' %> <small><i>required</i></small>
              <%= f.text_field :phone, :class => 'form-control', required: true %>
              <%=f.error_span(:phone) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-12">
            <h4>Contact and Map</h4>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :contact, :class => 'control-label' %> <small><i>required</i></small>
              <%= f.text_area :contact, :class => 'form-control', required: true, rows: 5 %>
              <%=f.error_span(:contact) %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :google_map, :class => 'control-label' %> <small><i>required</i></small>
              <%= f.text_area :google_map, :class => 'form-control', required: true, rows: 5 %>
              <%=f.error_span(:google_map) %>
            </div>
          </div>
          <div class="col-md-12 text-center">
            <div class="form-group">
              <%= f.submit 'Save', :class => 'btn btn-success' %>
              <%= link_to t('.cancel', :default => t("helpers.links.cancel")),setups_path, :class => 'btn btn-light' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/setups/edit.html.erb
<%- model_class = Setup -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title">Setup</h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item">
              Setup
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/setups/index.html.erb
<%- model_class = Setup -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:site_name) %></th>
      <th><%= model_class.human_attribute_name(:site_title) %></th>
      <th><%= model_class.human_attribute_name(:site_description) %></th>
      <th><%= model_class.human_attribute_name(:site_keywords) %></th>
      <th><%= model_class.human_attribute_name(:site_url) %></th>
      <th><%= model_class.human_attribute_name(:site_image) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @setups.each do |setup| %>
      <tr>
        <td><%= link_to setup.id, setup_path(setup) %></td>
        <td><%= setup.site_name %></td>
        <td><%= setup.site_title %></td>
        <td><%= setup.site_description %></td>
        <td><%= setup.site_keywords %></td>
        <td><%= setup.site_url %></td>
        <td><%= setup.site_image %></td>
        <td><%=l setup.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      setup_path(setup), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_setup_path(setup), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      setup_path(setup),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_setup_path,
            :class => 'btn btn-primary' %>

app/views/setups/new.html.erb
<%- model_class = Setup -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/setups/show.html.erb
<%- model_class = Setup -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:site_name) %>:</strong></dt>
  <dd><%= @setup.site_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:site_title) %>:</strong></dt>
  <dd><%= @setup.site_title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:site_description) %>:</strong></dt>
  <dd><%= @setup.site_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:site_keywords) %>:</strong></dt>
  <dd><%= @setup.site_keywords %></dd>
  <dt><strong><%= model_class.human_attribute_name(:site_url) %>:</strong></dt>
  <dd><%= @setup.site_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:site_image) %>:</strong></dt>
  <dd><%= @setup.site_image %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              setups_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_setup_path(@setup), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              setup_path(@setup),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>