config/routes.rb
Rails.application.routes.draw do



  scope "(:locale)", locale: /id|en/ do
    resources :ecommerce_products
    resources :ecommerces
    resources :discoverproducts
    resources :request_samples
    root 'pages#home'
    get 'app' => "app#index"
    get 'dashboard' => "app#index"

    get 'contact-us', to: 'pages#contact', as: :contact_us
    get 'home/discoverourproduct', to: 'pages#discoverourproduct', as: :discoverourproduct
    get 'discoverourproduct', to: 'pages#discoverourproduct'
    resources :users
    resources :setups
    resources :stores do
      collection { post :import }
    end
    resources :beasellers do
      collection { post :import }
    end
    resources :image_events
    resources :events
    resources :articles
    resources :image_products
    resources :product_categories
    resources :products
    devise_for :users,
    path:'user',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }
     get 'simulasi-keuntungan', to: 'pages#simulasikeuntungan', as: :simulasikeuntungan
     get 'beaseller', to: 'pages#beaseller', as: :crt_beaseller
     get 'requestsample', to: 'pages#requestsample', as: :crt_requestsample
     get 'list-page', to: 'pages#index', as: :list_pages
     get 'store-location', to: 'pages#storelocation', as: :storelocation

     get '/product', to: 'pages#list_product', as: :list_product
     get 'product/:id', to: 'product_categories#show', as: :dtl_product_category
     get 'product/:category_name/:id/', to: 'products#show', as: :dtl_product

     get '/thankspage', to: 'pages#thankspage', as: :thankspage
     get '/news-and-event', to: 'pages#list_blog', as: :gallery
     get '/blog', to: 'pages#list_blog', as: :list_blog
     get 'blog/:id', to: 'articles#show', as: :dtl_blog
     get '/event', to: 'pages#list_event', as: :list_event
     get '/event/:id', to: 'events#show', as: :dtl_event

     resources :pages, path: ''
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]

      new
      params =
      {store:
        {
          name: row["name"],
          area: row["area"],
          address: row["address"],
          lat: row["lat"],
          long: row["long"]
        }
       }
        Store.create(params[:store])
      end
    end

    def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path,file_warning: :ignore)
      when '.xls' then Roo::Excel.new(file.path,file_warning: :ignore)
      when '.xlsx' then Roo::Excelx.new(file.path,file_warning: :ignore)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end


end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  layout 'admin', except: [:show]
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Store.import(params[:file])
    redirect_to stores_path, notice: "Store imported."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def store_params
    params.require(:store).permit(:name, :area, :address, :lat, :long)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for @store, :html => { :class => "form-horizontal store" } do |f| %>

  <% if @store.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @store.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :area, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :area, :class => 'form-control' %>
    </div>
    <%=f.error_span(:area) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :lat, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lat, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lat) %>
  </div>
  <div class="form-group">
    <%= f.label :long, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :long, :class => 'form-control' %>
    </div>
    <%=f.error_span(:long) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                stores_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/stores/edit.html.erb
<%- model_class = Store -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= stores_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="card">
    <div class="card-body">
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>

app/views/stores/index.html.erb
<%- model_class = Store -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_store_path, :class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:name) %></th>
                <th><%= model_class.human_attribute_name(:area) %></th>
                <th><%= model_class.human_attribute_name(:address) %></th>
                <th><%= model_class.human_attribute_name(:lat) %></th>
                <th><%= model_class.human_attribute_name(:long) %></th>

                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @stores.each do |store| %>
              <tr>
                <td><%= link_to store.id, store_path(store) %></td>
                <td><%= store.name.truncate(20) %></td>
                <td><%= store.area %></td>
                <td><%= store.address.truncate(20) %></td>
                <td><%= store.lat %></td>
                <td><%= store.long %></td>

                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  store_path(store), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_store_path(store), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  store_path(store),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $(".table").dataTable();
  });
</script>

app/views/stores/new.html.erb
<%- model_class = Store -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= stores_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="card">
    <div class="card-body">
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>

app/views/stores/show.html.erb
<style type="text/css">
.coklat1{
  position: absolute;
  height: 180px;
  top: 12vh;
  right:3vw;
  z-index:10;
}
.coklat2{
  position: absolute;
  height: 180px;
  bottom: 3vh;
  right:1vw;
  z-index:5;
}
.coklat3{
  position: absolute;
  right: 0;
  bottom:20vh;
  width:200px;
}
.titlepage{
  font-size: 2rem;
  text-transform: uppercase;
  text-align: center;
  margin-bottom: 2rem;
  color:#0060af;
}
.paper p{
  text-transform: uppercase;
  letter-spacing: .2em;
  color:#0060af;
  font-weight: 300;
  font-size: .7em;
  line-height: 2;
  margin-bottom:1em;
}

p::first-letter,p .big{
  font-size: 1.5em;
  line-height: 1;
}

.table-striped tbody tr:nth-of-type(odd) {
  background-color: rgb(179, 232, 255);
  border: 0;
}
.table-striped tbody tr:nth-of-type(even) {

  background: #c4e7f6;
  border: 0;
}

.tabel td, .table th{
  font-family: 'Fredoka one';
  font-weight: 100;
  border: 0;
}

.txt-ket{
    font-size: 15px;
}

/* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 400px;
      }
@media (max-width: 769px){
  .paper{
    margin: 0 0px;
  }
  .coklat1,.coklat2{
    right:-6vw;
  }
  .paper > .wrappadding{
    min-height: 75vh;
  }
  .nanas8 {
    height: 80px;
    top: 18vh;
    left: 20vw;
  }
}
@media (max-width: 740px)
{
  .coklat1,.coklat2{
    right:0vw;
    max-height: 100px;
  }
  .coklat3 {
    max-width: 120px;
  }
  .nanas1{
    max-height: 100px;
  }
  .nanas2{
    max-height: 100px;
  }
  .nanas2{
    max-height: 120px;
    bottom: 10vh;
  }
  .contentterms{
    height: 70vh;
  }
  }@media (max-width: 500px)
  {
    p{
      text-indent:2rem;
      text-align: left;
    }
    .contentterms{
      height: 80vh;
    }
    .paper > .wrappadding{
      padding: 1.5rem 1.5rem 4rem 1.5rem;
    }
    .titlepage{
      font-size:1.3rem;
      margin-bottom: 1rem;
    }
    .coklat2{
      bottom:10vh;
    }
    .coklat1, .coklat2{
      right: -7vw;
    }
    .coklat3{
      bottom: 30vh;
    }
    .txt-ket{
    font-size: 11px;
}
  }
</style>

  <section id="contentsection" class="contentsection" >
    <div id="load" class="contenthomeslide contenview">

    <div id="wrappingshow">
      <div class="d-block" style="margin-top:25vh;padding-bottom:25vh">
        <div class="container xanimated animated opacity0">
          <h1 class="titlepage">TEMUKAN JOYDAY</h1>
          <div class="mb-5">
            <p class="text-center"> Anda Dapat Membeli produk Joyday di toko - toko terdekat di sekitar Anda, silahkan  cek di sini </p>
          </div>
          <div id="map"></div>
          <hr style="background-color:#285da2;">

          <div class="row">

              <div class="col-md-6 col-12 mb-3">
                <div class="card">
                  <div class="card-body">
                    <h3 class="mb-2"><%= @store.name %></h3>
                    <span style="font-size:0.7em" class="mb-3"><%= @store.address %></span> <br>
                    <a  style="font-size:0.6em" href="https://www.google.com/maps/dir/?api=1&destination=<%=@store.long %>,<%=@store.lat %>#" target="_blank">
                      Lihat di Google Map
                    </a>
                  </div>
                </div>
              </div>

          </div>
        </div>

      </div>
      <script type="text/javascript">
        $(document).ready(function(){
          $('.imgfooter').animate({'opacity':1, 'bottom' : 0},100,function(){


                $('.socmed,.socmedmobile,.headerhome').animate({'opacity':1},1000).removeClass('fadeIn');

                $('.socmed').animate({'opacity':1},1000).removeClass('fadeIn');
               setTimeout(function(){
                 $('.xanimated').animate({'opacity' : 1},1000,function(){

                 }).addClass('fadeInUp');
               },1000);


          }).addClass('fadeInUp').prev('.copyright').delay(1000).animate({opacity:1},1000);
        });
      </script>

      <script type="text/javascript">
        $("#selectLocation" ).change(function(){
          $('#filter-location').submit();
        });
      </script>
      <script>

        // This example displays a marker at the center of Australia.
        // When the user clicks the marker, an info window opens.

        function initMap() {
          var uluru = {lat: <%= @store.long %>, lng: <%= @store.lat %>};
          var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 20,
            center: uluru
          });

          var contentString = '<h5><a href="<%= store_path(@store.id) %>"><strong><%= @store.name %></strong></a><h5><span><%= @store.address %><span>';

          var infowindow = new google.maps.InfoWindow({
            content: contentString
          });

          var marker = new google.maps.Marker({
            position: uluru,
            map: map,
            title: '<%= @store.name %>'
          });
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });
        }
      </script>
      <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
      </script>
      <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBV7vH0yIM9wN_YJxqvacDESUNRRFYylKU&callback=initMap">
      </script>
      </div>

      </div>

    </section>
    <div class="copyright absolute animated opacity0">
      <div class="footermenu">
        <a href="/terms-of-use" data-href="" data-url="/terms-of-use" data-title="terms of use Joyday" class="firstmenu menufoot"><%= t('tandc') %></a>
        <a href="/privacy-policy" data-href="/privacy-policy" data-url="privacy-policy" data-title="Privacy Policy Joyday" class="firstmenu menufoot"><%= t('privacy_policy') %></a>
        <a href="/contact-us" data-href="/contact-us" data-url="home/contact" data-title="Contact Joyday" class="firstmenu menufoot"><%= t('contact_us') %></a>
      </div>
    </div>
    <div class="imgfooter imgfooter1 opacity0 animated">
      <img class="img-fluid img100percent" src="<%= asset_url('static/footer.png')%>" alt="shadowyellow"/>
    </div>
    <div class="imgfooter imgfooter2 opacity0 animated">
      <img class="img-fluid img100percent" src="<%= asset_url('static/footer2.png')%>" alt="shadowyellow"/>
    </div>
    <div class="imgfooter imgfooter3 opacity0 animated">
      <img class="img-fluid img100percent" src="<%= asset_url('static/footer3.png')%>" alt="shadowyellow"/>
    </div>