config/routes.rb
Rails.application.routes.draw do



  scope "(:locale)", locale: /id|en/ do
    resources :ecommerce_products
    resources :ecommerces
    resources :discoverproducts
    resources :request_samples
    root 'pages#home'
    get 'app' => "app#index"
    get 'dashboard' => "app#index"

    get 'contact-us', to: 'pages#contact', as: :contact_us
    get 'home/discoverourproduct', to: 'pages#discoverourproduct', as: :discoverourproduct
    get 'discoverourproduct', to: 'pages#discoverourproduct'
    resources :users
    resources :setups
    resources :stores do
      collection { post :import }
    end
    resources :beasellers do
      collection { post :import }
    end
    resources :image_events
    resources :events
    resources :articles
    resources :image_products
    resources :product_categories
    resources :products
    devise_for :users,
    path:'user',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }
     get 'simulasi-keuntungan', to: 'pages#simulasikeuntungan', as: :simulasikeuntungan
     get 'beaseller', to: 'pages#beaseller', as: :crt_beaseller
     get 'requestsample', to: 'pages#requestsample', as: :crt_requestsample
     get 'list-page', to: 'pages#index', as: :list_pages
     get 'store-location', to: 'pages#storelocation', as: :storelocation

     get '/product', to: 'pages#list_product', as: :list_product
     get 'product/:id', to: 'product_categories#show', as: :dtl_product_category
     get 'product/:category_name/:id/', to: 'products#show', as: :dtl_product

     get '/thankspage', to: 'pages#thankspage', as: :thankspage
     get '/news-and-event', to: 'pages#list_blog', as: :gallery
     get '/blog', to: 'pages#list_blog', as: :list_blog
     get 'blog/:id', to: 'articles#show', as: :dtl_blog
     get '/event', to: 'pages#list_event', as: :list_event
     get '/event/:id', to: 'events#show', as: :dtl_event

     resources :pages, path: ''
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discoverproduct.rb
class Discoverproduct < ApplicationRecord
  mount_uploader :tp_1_image_1, ImageUploader
  mount_uploader :tp_1_image_2, ImageUploader
  mount_uploader :tp_1_image_3, ImageUploader
  mount_uploader :tp_1_image_4, ImageUploader
  mount_uploader :tp_1_image_1_en, ImageUploader
  mount_uploader :tp_1_image_2_en, ImageUploader
  mount_uploader :tp_1_image_3_en, ImageUploader
  mount_uploader :tp_1_image_4_en, ImageUploader
  mount_uploader :full_image, ImageUploader
  mount_uploader :full_image_mobile, ImageUploader
  mount_uploader :background,ImageUploader
  mount_uploader :main,ImageUploader
  mount_uploader :background_en,ImageUploader
  mount_uploader :main_en,ImageUploader
  mount_uploader :animated_1, ImageUploader
  mount_uploader :animated_2, ImageUploader
  mount_uploader :animated_3, ImageUploader
  mount_uploader :animated_4, ImageUploader
  mount_uploader :animated_5, ImageUploader
  mount_uploader :animated_6, ImageUploader
  mount_uploader :animated_7, ImageUploader
  mount_uploader :animated_8, ImageUploader
  mount_uploader :animated_9, ImageUploader
  mount_uploader :main_mbl, ImageUploader
  mount_uploader :background_mbl, ImageUploader
  mount_uploader :effect_1_mbl, ImageUploader
  mount_uploader :effect_2_mbl, ImageUploader
  mount_uploader :effect_3_mbl, ImageUploader
  mount_uploader :effect_4_mbl, ImageUploader
  mount_uploader :main_mbl_en, ImageUploader
  mount_uploader :background_mbl_en, ImageUploader
  mount_uploader :effect_1_en_mbl, ImageUploader
  mount_uploader :effect_2_en_mbl, ImageUploader
  mount_uploader :effect_3_en_mbl, ImageUploader
  mount_uploader :effect_4_en_mbl, ImageUploader 

  mount_uploader :background,ImageUploader

  Templated = ["Simple", "Template 1",  "Template 11", "Template 12" ]


  # animated template 1 nanas 7
  # animated template 2 jujube 5
  # animated template 3 honeydew 5
  # animated template 4 ccv 6
  # animated template 5 ccm 5
  # animated template 6 ccb 4
  # animated template 7 sc 5
  # animated template 8 bb 6
  # animated template 9 cpa 7
  # animated template 10 milky 5
  # animated template 11 mocha 5
  # animated template 12 bean 9


  def remove_image=(val)
    image_will_change! if val
    super
  end

end

app/controllers/discoverproducts_controller.rb
class DiscoverproductsController < ApplicationController
  before_action :set_discoverproduct, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'admin'
  # GET /discoverproducts
  # GET /discoverproducts.json
  def index
    @discoverproducts = Discoverproduct.all
  end

  # GET /discoverproducts/1
  # GET /discoverproducts/1.json
  def show
  end

  # GET /discoverproducts/new
  def new
    @discoverproduct = Discoverproduct.new
  end

  # GET /discoverproducts/1/edit
  def edit
  end

  # POST /discoverproducts
  # POST /discoverproducts.json
  def create
    @discoverproduct = Discoverproduct.new(discoverproduct_params)

    respond_to do |format|
      if @discoverproduct.save
        format.html { redirect_to discoverourproduct_path, notice: 'Discoverproduct was successfully created.' }
        format.json { render :show, status: :created, location: @discoverproduct }
      else
        format.html { render :new }
        format.json { render json: @discoverproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discoverproducts/1
  # PATCH/PUT /discoverproducts/1.json
  def update
    respond_to do |format|
      if @discoverproduct.update(discoverproduct_params)
        format.html { redirect_to discoverourproduct_path, notice: 'Discoverproduct was successfully updated.' }
        format.json { render :show, status: :ok, location: @discoverproduct }
      else
        format.html { render :edit }
        format.json { render json: @discoverproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discoverproducts/1
  # DELETE /discoverproducts/1.json
  def destroy
    @discoverproduct.destroy
    respond_to do |format|
      format.html { redirect_to discoverproducts_url, notice: 'Discoverproduct was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discoverproduct
      @discoverproduct = Discoverproduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discoverproduct_params
      params.require(:discoverproduct).permit(:title_id, :title_en, :content_id, :content_en, :tp_1_image_1, :tp_1_image_2, :tp_1_image_3, :tp_1_image_4,:tp_1_image_1_en, :tp_1_image_2_en, :tp_1_image_3_en, :tp_1_image_4_en, :full_image, :full_image_mobile,  :full_image_en, :full_image_mobile_en, :link, :custom, :main, :background,:main_en, :background_en, :slider_type, :custom_code, :remove_main,:remove_main_en, :remove_background_en,:remove_tp_1_image_1, :remove_tp_1_image_2, :remove_tp_1_image_3, :remove_tp_1_image_4, :remove_tp_1_image_1_en, :remove_tp_1_image_2_en, :remove_tp_1_image_3_en, :remove_tp_1_image_4_en, :hide_title, :main_mbl, :background_mbl, :effect_1_mbl, :effect_2_mbl, :effect_3_mbl, :effect_4_mbl, :main_mbl_en, :background_mbl_en, :effect_1_en_mbl, :effect_2_en_mbl, :effect_3_en_mbl, :effect_4_en_mbl,  :animated_1,:animated_2,:animated_3,:animated_4,:animated_5,:animated_6,:animated_7,:animated_8,:animated_9,:main_mbl, :remove_background_mbl, :remove_effect_1_mbl, :remove_effect_2_mbl, :remove_effect_3_mbl, :remove_effect_4_mbl, :remove_main_mbl_en, :remove_background_mbl_en, :remove_effect_1_en_mbl, :remove_effect_2_en_mbl, :remove_effect_3_en_mbl, :remove_effect_4_en_mbl,  :remove_animated_1,:remove_animated_2,:remove_animated_3,:remove_animated_4,:remove_animated_5,:remove_animated_6,:remove_animated_7,:remove_animated_8,:remove_animated_9, :animated_type)
    end
end

app/helpers/discoverproducts_helper.rb
module DiscoverproductsHelper
end

app/views/discoverproducts/edit.html.erb
<%- model_class = Discoverproduct -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/discoverproducts/index.html.erb
<%- model_class = Discoverproduct -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <button type="button" class="btn btn-success mb-2" data-toggle="modal" data-target="#exampleModal">
            New
          </button>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:title_id) %></th>
                <th><%= model_class.human_attribute_name(:slider_type) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @discoverproducts.each do |discoverproduct| %>
              <tr>
                <td><%= link_to discoverproduct.id, discoverproduct_path(discoverproduct) %></td>
                <td><%= discoverproduct.title_id %></td>

                <td><%= discoverproduct.slider_type %></td>
                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  discoverproduct_path(discoverproduct), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_discoverproduct_path(discoverproduct), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  discoverproduct_path(discoverproduct),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $(".table").dataTable();
  });
</script>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Select Template</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">

          <div class="col-md-4">
            <p>Slider  Animated Template</p>
            <%= link_to "Create with full image ", new_discoverproduct_path(slider_type: "animated"), :class => 'btn btn-success mb-2' %>
          </div>

          <div class="col-md-4">
            <p>Slider  Full Image</p>

            <%= link_to "Create with full image ", new_discoverproduct_path(slider_type: "full image"), :class => 'btn btn-success mb-2' %>
          </div>
          <div class="col-md-4">
            <p>Slider Type Custom Code</p>

            <%= link_to "Create with custom code", new_discoverproduct_path(slider_type: "custom code"), :class => 'btn btn-success mb-2' %>
            <p><small>check <a href="https://getbootstrap.com/docs/4.3/components/carousel/">getbootstrap.com</a></small> for documentation</p>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/discoverproducts/new.html.erb
<%- model_class = Discoverproduct -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %> <%= params[:slider_type] %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= articles_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
<%= render :partial => 'form' %>
</div>

app/views/discoverproducts/show.html.erb
<%- model_class = Discoverproduct -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title_id) %>:</strong></dt>
  <dd><%= @discoverproduct.title_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title_en) %>:</strong></dt>
  <dd><%= @discoverproduct.title_en %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content_id) %>:</strong></dt>
  <dd><%= @discoverproduct.content_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content_en) %>:</strong></dt>
  <dd><%= @discoverproduct.content_en %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tp_1_image_1) %>:</strong></dt>
  <dd><%= @discoverproduct.tp_1_image_1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tp_1_image_2) %>:</strong></dt>
  <dd><%= @discoverproduct.tp_1_image_2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tp_1_image_3) %>:</strong></dt>
  <dd><%= @discoverproduct.tp_1_image_3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tp_1_image_4) %>:</strong></dt>
  <dd><%= @discoverproduct.tp_1_image_4 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tp_1_image_5) %>:</strong></dt>
  <dd><%= @discoverproduct.tp_1_image_5 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tp_image_6) %>:</strong></dt>
  <dd><%= @discoverproduct.tp_image_6 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tp_2_image_1) %>:</strong></dt>
  <dd><%= @discoverproduct.tp_2_image_1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tp_2_image_3) %>:</strong></dt>
  <dd><%= @discoverproduct.tp_2_image_3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tp_3_image_3) %>:</strong></dt>
  <dd><%= @discoverproduct.tp_3_image_3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tp_3_image_4) %>:</strong></dt>
  <dd><%= @discoverproduct.tp_3_image_4 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:full_image) %>:</strong></dt>
  <dd><%= @discoverproduct.full_image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= @discoverproduct.link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:custom) %>:</strong></dt>
  <dd><%= @discoverproduct.main %></dd>
  <dd><%= @discoverproduct.background %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              discoverproducts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_discoverproduct_path(@discoverproduct), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              discoverproduct_path(@discoverproduct),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>