config/routes.rb
Rails.application.routes.draw do



  scope "(:locale)", locale: /id|en/ do
    resources :ecommerce_products
    resources :ecommerces
    resources :discoverproducts
    resources :request_samples
    root 'pages#home'
    get 'app' => "app#index"
    get 'dashboard' => "app#index"

    get 'contact-us', to: 'pages#contact', as: :contact_us
    get 'home/discoverourproduct', to: 'pages#discoverourproduct', as: :discoverourproduct
    get 'discoverourproduct', to: 'pages#discoverourproduct'
    resources :users
    resources :setups
    resources :stores do
      collection { post :import }
    end
    resources :beasellers do
      collection { post :import }
    end
    resources :image_events
    resources :events
    resources :articles
    resources :image_products
    resources :product_categories
    resources :products
    devise_for :users,
    path:'user',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }
     get 'simulasi-keuntungan', to: 'pages#simulasikeuntungan', as: :simulasikeuntungan
     get 'beaseller', to: 'pages#beaseller', as: :crt_beaseller
     get 'requestsample', to: 'pages#requestsample', as: :crt_requestsample
     get 'list-page', to: 'pages#index', as: :list_pages
     get 'store-location', to: 'pages#storelocation', as: :storelocation

     get '/product', to: 'pages#list_product', as: :list_product
     get 'product/:id', to: 'product_categories#show', as: :dtl_product_category
     get 'product/:category_name/:id/', to: 'products#show', as: :dtl_product

     get '/thankspage', to: 'pages#thankspage', as: :thankspage
     get '/news-and-event', to: 'pages#list_blog', as: :gallery
     get '/blog', to: 'pages#list_blog', as: :list_blog
     get 'blog/:id', to: 'articles#show', as: :dtl_blog
     get '/event', to: 'pages#list_event', as: :list_event
     get '/event/:id', to: 'events#show', as: :dtl_event

     resources :pages, path: ''
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :username
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :role, presence: true
  validates :email, presence: true

  mount_uploader :avatar, AvatarUploader

  ROLES = {root:'root',administrator:'administrator',author:'author', editor:'editor'}
  scope :root, -> {where(role: ROLES[:root])}
  scope :administrator, -> {where(role: ROLES[:administrator])}
  scope :author, -> {where(role: ROLES[:author])}
  scope :editor, -> {where(role: ROLES[:editor])}
  def is_root?
    self.role == ROLES[:root]
  end
  def is_administrator?
    self.role == ROLES[:administrator]
  end
  def is_author?
    self.role == ROLES[:author]
  end
  def is_editor?
    self.role == ROLES[:editor]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'admin'
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if params[:editpass].present?
        if @user_with_password.update_with_password(user_params_password)
          format.html { redirect_to @user, notice: 'User Password was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
      @user_with_password = User.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :slug, :email, :name, :role, :gender, :bio, :avatar,:password, :password_confirmation)
    end

    def user_params_password
      params.require(:user).permit(:current_password,:password,:password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    <h3 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <%= pluralize(@user.errors.count, "error") %> </h3>
    <p>prohibited this user from being saved:</p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <div class="form-group">
          <%= f.label :avatar, :class => 'control-label' %>
          <%= f.file_field :avatar, :class => 'dropify','data-height'=>"300",'data-max-file-size'=>'500K','data-allowed-formats'=>'square' %>
          <%=f.error_span(:avatar) %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :username, :class => 'control-label' %> <small><i>Required</i></small>
              <%= f.text_field :username, :class => 'form-control', required: true %>
              <%=f.error_span(:username) %>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <%= f.label :name, :class => 'control-label' %>
              <%= f.text_field :name, :class => 'form-control' %>
              <%=f.error_span(:name) %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :email, :class => 'control-label' %> <small><i>Required</i></small>
              <%= f.text_field :email, :class => 'form-control', required: true %>
              <%=f.error_span(:email) %>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <%= f.label :role, :class => 'control-label' %> <small><i>Required</i></small>
              <%= f.select :role, User::ROLES.map {|r| [r.last.to_s, r.last.to_s] }, {:include_blank => '- Choose -'}, :class => 'form-control',:required => true %>
              <%=f.error_span(:role) %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :bio, :class => 'control-label' %>
              <%= f.text_area :bio, :class => 'form-control' %>
              <%=f.error_span(:bio) %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.label :password, :class => 'control-label' %> <small><i>Required</i></small>
            <%= f.password_field :password, :class => 'form-control', required:true %>
            <%=f.error_span(:password) %>
          </div>
          <div class="col">
            <%= f.label :password_confirmation, :class => 'control-label' %> <small><i>Required</i></small>
            <%= f.password_field :password_confirmation, :class => 'form-control', required:true %>
            <%=f.error_span(:password_confirmation) %>
          </div>
        </div>
        <div class="row">
          <div class="col text-center">
            <div class="form-group mt-3">
              <%= f.submit nil, :class => 'btn btn-success' %>
              <%= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-light' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/_formedit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    <h3 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <%= pluralize(@user.errors.count, "error") %> </h3>
    <p>prohibited this user from being saved:</p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <div class="form-group">
          <%= f.label :avatar, :class => 'control-label' %>
          <% if @user.avatar.nil? %>
            <%= f.file_field :avatar, :class => 'dropify','data-height'=>"300",'data-max-file-size'=>'500K','data-allowed-formats'=>'square' %>
          <% else %>
            <%= f.file_field :avatar, :class => 'dropify','data-height'=>"300",'data-max-file-size'=>'500K','data-allowed-formats'=>'square', 'data-default-file' => @user.avatar.url %>
          <% end %>
          <%=f.error_span(:avatar) %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :username, :class => 'control-label' %> <small><i>Required</i></small>
              <%= f.text_field :username, :class => 'form-control', required: true %>
              <%=f.error_span(:username) %>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <%= f.label :name, :class => 'control-label' %>
              <%= f.text_field :name, :class => 'form-control' %>
              <%=f.error_span(:name) %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :email, :class => 'control-label' %> <small><i>Required</i></small>
              <%= f.text_field :email, :class => 'form-control', required: true %>
              <%=f.error_span(:email) %>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <%= f.label :role, :class => 'control-label' %> <small><i>Required</i></small>
              <%= f.select :role, User::ROLES.map {|r| [r.last.to_s, r.last.to_s] }, {:include_blank => '- Choose -'}, :class => 'form-control',:required => true %>
              <%=f.error_span(:role) %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :bio, :class => 'control-label' %>
              <%= f.text_area :bio, :class => 'form-control' %>
              <%=f.error_span(:bio) %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col text-center">
            <div class="form-group mt-3">
              <%= f.submit nil, :class => 'btn btn-success' %>
              <%= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-light' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<%= form_for @user_with_password, :html => { :class => "form-horizontal user" } do |f| %>
<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <h3>Change Password</h3>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :current_password, :class => 'control-label' %>
              <%= f.password_field :current_password, :class => 'form-control',:required => true %>
              <%=f.error_span(:current_password) %>
            </div>
          </div>
          <div class="col">
            <%= f.label :password, :class => 'control-label' %> <small><i>Required</i></small>
            <%= f.password_field :password, :class => 'form-control', required:true %>
            <%=f.error_span(:password) %>
          </div>
          <div class="col">
            <%= f.label :password_confirmation, :class => 'control-label' %> <small><i>Required</i></small>
            <%= f.password_field :password_confirmation, :class => 'form-control', required:true %>
            <%=f.error_span(:password_confirmation) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= users_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'formedit' %>
</div>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")),new_user_path,:class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:username) %></th>
                <th><%= model_class.human_attribute_name(:name) %></th>
                <th><%= model_class.human_attribute_name(:role) %></th>
                <th><%= model_class.human_attribute_name(:email) %></th>
                <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td><%= link_to user.id, user_path(user) %></td>
                <td><%= user.username %></td>
                <td><%= user.name %></td>
                <td><%= user.role %></td>
                <td><%= user.email %></td>
                <td><%= user.last_sign_in_at.strftime("%Y/%m/%d @%H:%M") rescue "-" rescue '-' %></td>
                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  user_path(user), :class => 'btn btn-info btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_user_path(user), :class => 'btn btn-warning btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  user_path(user),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $(".table").dataTable();
  });
</script>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= users_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title">User Profile</h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= users_path %>"><%= model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">User Profile</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <center class="mt-3">
            <% unless @user.avatar.nil? || @user.avatar.blank? %>
              <img src="<%= @user.avatar.url rescue '' %>" alt="" class="rounded-circle" width="150">
            <% else %>
              <img src="<%= asset_url('pikachu.png') %>" alt="" class="rounded-circle" width="150">
            <% end %>
            <h4 class="card-title m-t-10"><%= @user.username rescue '-' %></h4>
            <h6 class="card-subtitle"><%= @user.role %></h6>
          </center>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-3 col-xs-6 b-r">
              <strong><%= model_class.human_attribute_name(:name) %></strong>
              <p class="text-muted"><%= @user.name %></p>
            </div>
            <div class="col-md-3 col-xs-6 b-r">
              <strong><%= model_class.human_attribute_name(:email) %></strong>
              <p class="text-muted"><%= @user.email %></p>
            </div>
            <div class="col-md-3 col-xs-6 b-r">
              <strong><%= model_class.human_attribute_name(:last_sign_in_at) %></strong>
              <p class="text-muted"><%= @user.last_sign_in_at %></p>
            </div>
            <div class="col-md-12">
              <strong><%= model_class.human_attribute_name(:bio) %></strong>
              <p class="text-muted"><%= @user.bio %></p>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col text-center">
              <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-light'  %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-warning' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>